services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    ports:
      - 1883:1883
    volumes:
      - /opt/stacks/mosquitto:/mosquitto

  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=${ZWAVEJS2MQTT_SESSION_SECRET}
    devices:
      - /dev/serial/by-id/usb-0658_0200-if00:/dev/serial/by-id/usb-0658_0200-if00
    volumes:
      - /opt/stacks/zwavejs2mqtt/store:/usr/src/app/store
    ports:
      - 8091:8091 # port for web interface
      - 3000:3000 # port for zwave-js websocket server

  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: always
    image: ghcr.io/koenkk/zigbee2mqtt:latest
    volumes:
      - /opt/stacks/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      - TZ=${TZ}
    devices:
      - /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0:/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
networks: {}