services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - hass_config:/config
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev:/dev
      
  piper:
    image: lscr.io/linuxserver/piper:latest
    container_name: piper
    environment:
      - VOICE=zh_CN-huayan-medium
    #command: --voice zh-CN-huayan --voice en_US-amy
    volumes:
      - piper_data:/config
    ports:
      - 10200:10200
    restart: unless-stopped      

  whisper:
    container_name: whisper
    image: rhasspy/wyoming-whisper
    restart: unless-stopped
    ports:
      - "10300:10300"
    volumes:
      - whisper_data:/data
    environment:
      - MODEL=medium
    command: --model medium --language auto

volumes:
  hass_config:
    name: hass_config
  piper_data:
    name: piper_data
  whisper_data:
    name: whisper_data