services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - hass_config:/config
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev:/dev
      - /etc/localtime:/etc/localtime:ro

volumes:
  hass_config:
    name: hass_config