version: "3.7"

services:

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    volumes:
      - ${USERDIR}/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}

  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:latest
    volumes:
      - ${USERDIR}/homeassistant/config:/config
    depends_on:
      - mariadb
    networks:
      - traefik-network
    ports:
      - "8123:8123"
      - "6666:6666/udp" #localtuya
      - "6667:6667/udp" #localtuya
      - "136:136/udp"
    expose:
      - 6666/udp
      - 6667/udp
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant.rule=Host(`${HA_HOST_NAME}`)"
      - "traefik.http.routers.homeassistant.entrypoints=websecure"
      - "traefik.http.routers.homeassistant.tls.certresolver=myresolver"
      - traefik.http.services.homeassistant.loadbalancer.server.port=8123

  tasmoadmin:
    container_name: tasmoadmin
    image: raymondmm/tasmoadmin:latest
    ports:
      - "9900:80"
    volumes:
      - ${USERDIR}/tasmoadmin:/data

  tasmobackup:
    image: "danmed/tasmobackupv1"
    container_name: tasmobackup
    ports:
      - "8259:80"
    volumes:
      - ${USERDIR}/tasmobackup:/var/www/html/data
    environment:
      # MYSQL env's are not needed if you are using sqlite
      # - MYSQL_SERVER=192.168.1.4:3307
      # - MYSQL_USERNAME=tasmo
      # - MYSQL_PASSWORD=y3&ZKH2W7QTf
      # change below to mysql if you don't want to use sqlite
      # you will need to have a mysql server (set above) with a blank database already created.
      - DBTYPE=sqlite
      # if using Mysql remove the data/ from the below line
      # if using Sqlite the data/ is required!
      - DBNAME=data/tasmobackup

  webtrees:
    container_name: webtrees
    image: "dtjs48jkt/webtrees"
    restart: always
    volumes:
      - ${USERDIR}/webtrees/data:/var/www/html/data
    # ports:
    #   - 8088:80
    networks:
      - traefik-network
    environment:
      - DISABLE_SSL=TRUE
      - PORT=80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webtrees.rule=Host(`${TREE_HOST_NAME}`)"
      - "traefik.http.routers.webtrees.entrypoints=websecure"
      - "traefik.http.routers.webtrees.tls.certresolver=myresolver"
      - traefik.http.services.webtrees.loadbalancer.server.port=80

  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:latest
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8888:80"
      # - '3003:3000'
      # - '67:67/udp'
      # - '67:67/tcp'
      # - '68:68/udp'
      # - '443:443/tcp'
      # - '853:853/tcp'
      # - '3003:3000/tcp'
    volumes:
      - ${USERDIR}/adguardhome/work:/opt/adguardhome/work
      - ${USERDIR}/adguardhome/conf:/opt/adguardhome/conf
      - ${USERDIR}/adguardhome/certs:/opt/adguardhome/certs:ro

  traefik:
    container_name: traefik
    image: "traefik:latest"
    command:
      #- "--log.level=DEBUG"
      - "--accesslog.filepath=/etc/traefik/access.log"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=${EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/etc/traefik/letsencrypt/acme.json"
    networks:
      - traefik-network
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ${USERDIR}/traefik:/etc/traefik

  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      # - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      # - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/frigate/config.yml:/config/config.yml:ro
      - ${USERDIR}/frigate/db:/database
      - ${USERDIR}/frigate/media:/media/frigate
      # - ${USERDIR}/frigate/go2rtc:/config/go2rtc
      - /dev/bus/usb:/dev/bus/usb
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5050:5000"
      - "8554:8554" # restream feeds
    environment:
      FRIGATE_RTSP_PASSWORD: ${FRIGATE_RTSP_PASSWORD}

  homer:
    image: b4bz/homer
    #To build from source, comment previous line and uncomment below
    #build: .
    container_name: homer
    volumes:
      - ${USERDIR}/homer/:/www/assets
    ports:
      - 8081:8080
    user: 1000:1000 # default
    environment:
      - INIT_ASSETS=1 # default

networks:
  traefik-network:
    external: true
