version: "3.7"

services:

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    volumes:
      - ${USERDIR}/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}

  # mosquitto:
  #   image: eclipse-mosquitto:latest
  #   container_name: mosquitto
  #   restart: always
  #   ports:
  #     - 1883:1883
  #   volumes:
  #     - ${USERDIR}/mosquitto/config:/mosquitto/config
  #     - ${USERDIR}/mosquitto/data:/mosquitto/data
  #     - ${USERDIR}/mosquitto/log:/mosquitto/log

  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:latest
    volumes:
      - ${USERDIR}/homeassistant/config:/config
    depends_on:
      - mariadb
      - mosquitto
    networks:
      - traefik-network
    ports:
      - "8123:8123"
      - "6666:6666/udp" #localtuya
      - "6667:6667/udp" #localtuya
      - "136:136/udp"
    expose:
      - 6666/udp
      - 6667/udp
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant.rule=Host(`${HOST_NAME}`)"
      - "traefik.http.routers.homeassistant.entrypoints=websecure"
      - "traefik.http.routers.homeassistant.tls.certresolver=myresolver"

  tasmoadmin:
    container_name: tasmoadmin
    image: raymondmm/tasmoadmin:latest
    ports:
      - "9900:80"
    volumes:
      - ${USERDIR}/tasmoadmin:/data

  tasmobackup:
    image: "danmed/tasmobackupv1"
    container_name: tasmobackup
    ports:
      - "8259:80"
    volumes:
      - ${USERDIR}/tasmobackup:/var/www/html/data
    environment:
      # MYSQL env's are not needed if you are using sqlite
      # - MYSQL_SERVER=192.168.1.4:3307
      # - MYSQL_USERNAME=tasmo
      # - MYSQL_PASSWORD=y3&ZKH2W7QTf
      # change below to mysql if you don't want to use sqlite
      # you will need to have a mysql server (set above) with a blank database already created.
      - DBTYPE=sqlite
      # if using Mysql remove the data/ from the below line
      # if using Sqlite the data/ is required!
      - DBNAME=data/tasmobackup 

networks:
  traefik-network:
    external: true