services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - hass_config:/config
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev:/dev
      
  piper:
    container_name: piper
    image: rhasspy/wyoming-piper
    command: --voice zh_CN-huayan-medium
    volumes:
      - piper_data:/data
    environment:
      - TZ=${TZ}
    restart: unless-stopped
    ports:
      - 10200:10200    

  whisper:
    container_name: whisper
    image: rhasspy/wyoming-whisper
    command: --model tiny-int8 --language en
    volumes:
      - whisper_data:/data
    environment:
      - TZ=${TZ}
    restart: unless-stopped
    ports:
      - 10300:10300

volumes:
  hass_config:
    name: hass_config
  piper_data:
    name: piper_data
  whisper_data:
    name: whisper_data