services:
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    restart: always
    environment:
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_DBHOST: postgres15
      PAPERLESS_ADMIN_USER: admin
      PAPERLESS_ADMIN_PASSWORD: your_password
      PAPERLESS_OCR_LANGUAGES: eng chi-sim chi-tra
      PAPERLESS_TASK_WORKERS: 2
      PAPERLESS_THREADS_PER_WORKER: 2
      PAPERLESS_TIME_ZONE: America/Vancouver
      PAPERLESS_DATE_ORDER: MDY
      PAPERLESS_CONSUMER_RECURSIVE: true
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_CONSUMER_POLLING: 180
    volumes:
      - /opt/stacks/peperless-ngx/data:/usr/src/paperless/data
      - /mnt/paperless/media:/usr/src/paperless/media
      - /mnt/paperless/consume:/usr/src/paperless/consume
      - /mnt/paperless/export:/usr/src/paperless/export
    depends_on:
      - redis
      - postgres15
    ports:
      - 8000:8000
  redis:
    image: redis:alpine
    restart: always
  postgres15:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    volumes:
      - /opt/stacks/peperless-ngx/pgdata15:/var/lib/postgresql/data    
  tika:
     image: ghcr.io/paperless-ngx/tika:latest
     restart: unless-stopped

  gotenberg:
      image: docker.io/gotenberg/gotenberg:7.10
      restart: unless-stopped
      environment:
        CHROMIUM_DISABLE_ROUTES: 1
      command:
        - "gotenberg"
        - "--chromium-disable-javascript=true"
        - "--chromium-allow-list=file:///tmp/.*"
networks: {}
