services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    restart: unless-stopped
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128    
    environment:
      - PUID=${ENV_PUID}
      - PGID=${ENV_PGID}
      - TZ=${TIMEZONE}
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional      
    volumes:
      - ${USR_DIR}/jellyfin:/config
      - ${DATA_DIR}:/data/media