services:
  huginn:
    image: ghcr.io/huginn/huginn:latest
    container_name: ${HUGINN_CONTAINER_NAME}
    ports:
      - "${HUGINN_HTTP_PORT}:3000"
    environment:
      DOMAIN: "${HUGINN_DOMAIN}"
      PORT: "3000"
      APP_SECRET_TOKEN: "${HUGINN_APP_SECRET_TOKEN}"
      DATABASE_ADAPTER: "mysql2"
      DATABASE_ENCODING: "utf8mb4"
      DATABASE_RECONNECT: "true"
      DATABASE_NAME: "${HUGINN_DB_NAME}"
      DATABASE_USERNAME: "${HUGINN_DB_USER}"
      DATABASE_PASSWORD: "${HUGINN_DB_PASS}"
      DATABASE_HOST: "${HUGINN_DB_HOST}"
      DATABASE_PORT: "${HUGINN_DB_PORT}"
      RAILS_ENV: "production"
      FORCE_SSL: "${HUGINN_FORCE_SSL}"
      TIMEZONE: "${HUGINN_TIMEZONE}"
      INVITATION_CODE: "${HUGINN_INVITATION_CODE}"
      SKIP_INVITATION_CODE: "${HUGINN_SKIP_INVITATION_CODE}"
      REQUIRE_CONFIRMED_EMAIL: "${HUGINN_REQUIRE_CONFIRMED_EMAIL}"
    restart: unless-stopped